# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "rspec"
gem "rubycritic"
gem "rake"
gem "reek"
gem "sandi_meter"
gem 'rubycritic-small-badge', :require => false